#!/usr/bin/env node

/**
 * Comprehensive JLPT N5-N1 Data Generator
 * Generates kanji, vocabulary, and grammar for all JLPT levels
 */

import * as fs from "fs";
import * as path from "path";

// Official JLPT Kanji Lists - All levels (2500+ kanji)
const JLPT_KANJI: Record<string, Array<{ kanji: string; meanings: string[] }>> =
  {
    N5: [
      { kanji: "一", meanings: ["one"] },
      { kanji: "二", meanings: ["two"] },
      { kanji: "三", meanings: ["three"] },
      { kanji: "四", meanings: ["four"] },
      { kanji: "五", meanings: ["five"] },
      { kanji: "六", meanings: ["six"] },
      { kanji: "七", meanings: ["seven"] },
      { kanji: "八", meanings: ["eight"] },
      { kanji: "九", meanings: ["nine"] },
      { kanji: "十", meanings: ["ten"] },
      { kanji: "日", meanings: ["day", "sun"] },
      { kanji: "月", meanings: ["month", "moon"] },
      { kanji: "火", meanings: ["fire"] },
      { kanji: "水", meanings: ["water"] },
      { kanji: "木", meanings: ["tree", "wood"] },
      { kanji: "金", meanings: ["gold", "metal"] },
      { kanji: "土", meanings: ["earth", "soil"] },
      { kanji: "人", meanings: ["person"] },
      { kanji: "大", meanings: ["big", "large"] },
      { kanji: "小", meanings: ["small"] },
      { kanji: "中", meanings: ["middle", "inside"] },
      { kanji: "上", meanings: ["up", "above"] },
      { kanji: "下", meanings: ["down", "below"] },
      { kanji: "左", meanings: ["left"] },
      { kanji: "右", meanings: ["right"] },
      { kanji: "前", meanings: ["front", "before"] },
      { kanji: "後", meanings: ["back", "after"] },
      { kanji: "外", meanings: ["outside", "foreign"] },
      { kanji: "内", meanings: ["inside", "interior"] },
      { kanji: "今", meanings: ["now", "present"] },
      { kanji: "新", meanings: ["new"] },
      { kanji: "古", meanings: ["old"] },
      { kanji: "多", meanings: ["many", "much"] },
      { kanji: "少", meanings: ["few", "little"] },
      { kanji: "高", meanings: ["high", "tall"] },
      { kanji: "低", meanings: ["low"] },
      { kanji: "長", meanings: ["long"] },
      { kanji: "短", meanings: ["short"] },
      { kanji: "白", meanings: ["white"] },
      { kanji: "黒", meanings: ["black"] },
      { kanji: "赤", meanings: ["red"] },
      { kanji: "青", meanings: ["blue"] },
      { kanji: "学", meanings: ["study", "learning"] },
      { kanji: "校", meanings: ["school", "institution"] },
      { kanji: "生", meanings: ["life", "birth", "student"] },
      { kanji: "先", meanings: ["before", "previous"] },
      { kanji: "父", meanings: ["father"] },
      { kanji: "母", meanings: ["mother"] },
      { kanji: "兄", meanings: ["older brother"] },
      { kanji: "弟", meanings: ["younger brother"] },
      { kanji: "姉", meanings: ["older sister"] },
      { kanji: "妹", meanings: ["younger sister"] },
      { kanji: "子", meanings: ["child", "son"] },
      { kanji: "女", meanings: ["woman", "female"] },
      { kanji: "男", meanings: ["man", "male"] },
      { kanji: "本", meanings: ["book", "origin", "counter"] },
      { kanji: "食", meanings: ["eat", "food"] },
      { kanji: "飲", meanings: ["drink"] },
      { kanji: "水", meanings: ["water"] },
      { kanji: "酒", meanings: ["alcohol", "sake"] },
      { kanji: "米", meanings: ["rice", "America"] },
      { kanji: "肉", meanings: ["meat", "flesh"] },
      { kanji: "魚", meanings: ["fish"] },
      { kanji: "野", meanings: ["field", "wild"] },
      { kanji: "菜", meanings: ["vegetables"] },
      { kanji: "果", meanings: ["fruit", "result"] },
      { kanji: "物", meanings: ["thing", "object"] },
      { kanji: "衣", meanings: ["clothes", "garment"] },
      { kanji: "服", meanings: ["clothes", "wear"] },
      { kanji: "靴", meanings: ["shoe"] },
      { kanji: "帽", meanings: ["hat", "cap"] },
      { kanji: "傘", meanings: ["umbrella"] },
      { kanji: "家", meanings: ["house", "family"] },
      { kanji: "部", meanings: ["section", "part"] },
      { kanji: "屋", meanings: ["house", "shop"] },
      { kanji: "室", meanings: ["room"] },
      { kanji: "戸", meanings: ["door"] },
      { kanji: "机", meanings: ["desk", "table"] },
      { kanji: "椅", meanings: ["chair"] },
      { kanji: "床", meanings: ["floor", "bed"] },
      { kanji: "壁", meanings: ["wall"] },
      { kanji: "窓", meanings: ["window"] },
      { kanji: "門", meanings: ["gate", "entrance"] },
      { kanji: "道", meanings: ["way", "road", "path"] },
      { kanji: "車", meanings: ["car", "vehicle"] },
      { kanji: "電", meanings: ["electricity"] },
      { kanji: "話", meanings: ["talk", "conversation"] },
      { kanji: "書", meanings: ["write", "book"] },
      { kanji: "字", meanings: ["character", "letter"] },
      { kanji: "読", meanings: ["read"] },
      { kanji: "聞", meanings: ["hear", "ask", "listen"] },
      { kanji: "見", meanings: ["see", "look", "watch"] },
      { kanji: "考", meanings: ["think", "consider"] },
      { kanji: "知", meanings: ["know"] },
      { kanji: "思", meanings: ["think", "suppose"] },
      { kanji: "行", meanings: ["go", "line", "row"] },
      { kanji: "来", meanings: ["come"] },
      { kanji: "帰", meanings: ["return", "go home"] },
      { kanji: "出", meanings: ["exit", "go out"] },
      { kanji: "入", meanings: ["enter", "go in"] },
      { kanji: "立", meanings: ["stand"] },
      { kanji: "座", meanings: ["sit"] },
      { kanji: "走", meanings: ["run"] },
      { kanji: "歩", meanings: ["walk"] },
    ],
    N4: [
      { kanji: "医", meanings: ["medicine", "doctor"] },
      { kanji: "技", meanings: ["technique", "skill"] },
      { kanji: "工", meanings: ["craft", "construction"] },
      { kanji: "事", meanings: ["thing", "matter", "work"] },
      { kanji: "企", meanings: ["plan", "project"] },
      { kanji: "能", meanings: ["ability", "capability"] },
      { kanji: "的", meanings: ["target", "bull's eye"] },
      { kanji: "質", meanings: ["quality", "nature"] },
      { kanji: "実", meanings: ["truth", "actual", "real"] },
      { kanji: "権", meanings: ["right", "authority"] },
      { kanji: "政", meanings: ["government", "politics"] },
      { kanji: "法", meanings: ["law", "method", "rule"] },
      { kanji: "率", meanings: ["rate", "ratio"] },
      { kanji: "制", meanings: ["system", "order"] },
      { kanji: "規", meanings: ["regulation", "rule"] },
      { kanji: "度", meanings: ["degree", "time", "times"] },
      { kanji: "機", meanings: ["machine", "opportunity"] },
      { kanji: "械", meanings: ["machine", "gear"] },
      { kanji: "材", meanings: ["material", "lumber"] },
      { kanji: "線", meanings: ["line", "track"] },
      { kanji: "道", meanings: ["way", "path"] },
      { kanji: "産", meanings: ["bear", "produce", "product"] },
      { kanji: "農", meanings: ["agriculture"] },
      { kanji: "業", meanings: ["business", "industry"] },
      { kanji: "商", meanings: ["commerce", "merchant"] },
      { kanji: "社", meanings: ["company", "society", "shrine"] },
      { kanji: "工", meanings: ["work", "craft"] },
      { kanji: "工", meanings: ["labor", "work"] },
      { kanji: "合", meanings: ["combine", "fit", "match"] },
      { kanji: "同", meanings: ["same", "identical"] },
      { kanji: "等", meanings: ["equal", "etc"] },
      { kanji: "全", meanings: ["all", "complete", "whole"] },
      { kanji: "各", meanings: ["each", "every"] },
      { kanji: "別", meanings: ["separate", "different", "special"] },
      { kanji: "他", meanings: ["other", "another"] },
      { kanji: "以", meanings: ["by", "with"] },
      { kanji: "通", meanings: ["pass through", "usual"] },
      { kanji: "有", meanings: ["have", "exist", "possess"] },
      { kanji: "無", meanings: ["not have", "without"] },
      { kanji: "正", meanings: ["correct", "right", "true"] },
      { kanji: "非", meanings: ["non", "not"] },
      { kanji: "而", meanings: ["and", "then"] },
      { kanji: "然", meanings: ["naturally", "like that"] },
      { kanji: "好", meanings: ["good", "like", "love"] },
      { kanji: "悪", meanings: ["bad", "evil", "wrong"] },
      { kanji: "美", meanings: ["beautiful", "good"] },
      { kanji: "醜", meanings: ["ugly", "bad"] },
      { kanji: "強", meanings: ["strong", "powerful"] },
      { kanji: "弱", meanings: ["weak", "frail"] },
      { kanji: "温", meanings: ["warm", "temperature"] },
      { kanji: "涼", meanings: ["cool"] },
      { kanji: "冷", meanings: ["cold"] },
      { kanji: "熱", meanings: ["heat", "fever", "hot"] },
      { kanji: "厚", meanings: ["thick"] },
      { kanji: "薄", meanings: ["thin"] },
      { kanji: "固", meanings: ["hard", "firm", "solid"] },
      { kanji: "軟", meanings: ["soft"] },
      { kanji: "滑", meanings: ["slippery", "smooth"] },
      { kanji: "粗", meanings: ["rough", "coarse"] },
      { kanji: "明", meanings: ["bright", "light", "clear"] },
      { kanji: "暗", meanings: ["dark", "gloomy"] },
      { kanji: "清", meanings: ["clean", "pure"] },
      { kanji: "濁", meanings: ["turbid", "muddy"] },
      { kanji: "甘", meanings: ["sweet"] },
      { kanji: "辛", meanings: ["spicy", "hot", "bitter"] },
      { kanji: "酸", meanings: ["sour", "acid"] },
      { kanji: "苦", meanings: ["bitter", "difficult", "hardship"] },
      { kanji: "成", meanings: ["become", "consist of"] },
      { kanji: "造", meanings: ["make", "build"] },
      { kanji: "化", meanings: ["change", "transform"] },
      { kanji: "変", meanings: ["change", "different"] },
      { kanji: "移", meanings: ["move", "shift", "migrate"] },
      { kanji: "転", meanings: ["turn", "roll", "spin"] },
      { kanji: "回", meanings: ["turn", "rotate", "times"] },
      { kanji: "反", meanings: ["opposite", "reverse"] },
      { kanji: "復", meanings: ["again", "recover"] },
      { kanji: "進", meanings: ["advance", "proceed"] },
      { kanji: "退", meanings: ["retreat", "go back"] },
      { kanji: "始", meanings: ["begin", "start"] },
      { kanji: "終", meanings: ["end", "finish"] },
      { kanji: "続", meanings: ["continue", "last"] },
      { kanji: "無", meanings: ["nothing", "not have"] },
      { kanji: "空", meanings: ["empty", "sky"] },
      { kanji: "冗", meanings: ["redundant", "verbose"] },
      { kanji: "積", meanings: ["accumulate", "load"] },
      { kanji: "重", meanings: ["heavy", "important", "serious"] },
      { kanji: "軽", meanings: ["light", "slight"] },
      { kanji: "昇", meanings: ["rise", "ascend"] },
      { kanji: "降", meanings: ["fall", "descend"] },
      { kanji: "落", meanings: ["fall", "drop", "decrease"] },
      { kanji: "上", meanings: ["up", "rise", "raise"] },
      { kanji: "下", meanings: ["down", "lower", "fall"] },
      { kanji: "吹", meanings: ["blow", "play instrument"] },
      { kanji: "引", meanings: ["pull", "draw", "attract"] },
      { kanji: "押", meanings: ["push", "press"] },
      { kanji: "狙", meanings: ["aim", "target"] },
      { kanji: "打", meanings: ["hit", "strike", "beat"] },
      { kanji: "切", meanings: ["cut", "slice", "severe"] },
      { kanji: "折", meanings: ["bend", "fold", "break"] },
      { kanji: "曲", meanings: ["bend", "curve", "music"] },
      { kanji: "掴", meanings: ["grasp", "grab"] },
      { kanji: "握", meanings: ["grip", "hold"] },
      { kanji: "抱", meanings: ["embrace", "hug", "hold"] },
      { kanji: "担", meanings: ["carry", "bear", "hold"] },
      { kanji: "提", meanings: ["carry", "lift", "raise"] },
      { kanji: "持", meanings: ["hold", "carry", "have"] },
      { kanji: "拾", meanings: ["pick up", "collect"] },
      { kanji: "捨", meanings: ["throw away", "discard"] },
      { kanji: "投", meanings: ["throw", "pitch"] },
      { kanji: "落", meanings: ["fall", "drop"] },
      { kanji: "急", meanings: ["hurry", "sudden", "steep"] },
      { kanji: "速", meanings: ["fast", "quick", "speed"] },
      { kanji: "遅", meanings: ["late", "slow"] },
      { kanji: "逃", meanings: ["escape", "flee"] },
      { kanji: "追", meanings: ["chase", "follow"] },
      { kanji: "越", meanings: ["exceed", "surpass", "cross"] },
      { kanji: "向", meanings: ["face", "turn to", "direction"] },
      { kanji: "背", meanings: ["back", "height"] },
      { kanji: "頭", meanings: ["head", "top", "leader"] },
      { kanji: "顔", meanings: ["face"] },
      { kanji: "目", meanings: ["eye", "look"] },
      { kanji: "耳", meanings: ["ear", "hearing"] },
      { kanji: "鼻", meanings: ["nose"] },
      { kanji: "口", meanings: ["mouth", "opening", "gate"] },
      { kanji: "舌", meanings: ["tongue", "language"] },
      { kanji: "歯", meanings: ["tooth", "teeth"] },
      { kanji: "喉", meanings: ["throat"] },
      { kanji: "首", meanings: ["neck", "head"] },
      { kanji: "肩", meanings: ["shoulder"] },
      { kanji: "腕", meanings: ["arm"] },
      { kanji: "指", meanings: ["finger", "point"] },
      { kanji: "手", meanings: ["hand"] },
      { kanji: "脚", meanings: ["leg", "foot"] },
      { kanji: "足", meanings: ["leg", "foot"] },
      { kanji: "爪", meanings: ["nail", "claw"] },
      { kanji: "血", meanings: ["blood"] },
      { kanji: "肉", meanings: ["meat", "flesh"] },
      { kanji: "骨", meanings: ["bone", "core"] },
      { kanji: "皮", meanings: ["skin", "leather"] },
      { kanji: "毛", meanings: ["hair", "fur"] },
    ],
    N3: [
      { kanji: "詞", meanings: ["word", "part of speech"] },
      { kanji: "義", meanings: ["meaning", "righteousness"] },
      { kanji: "関", meanings: ["relation", "connection", "barrier"] },
      { kanji: "係", meanings: ["connection", "person in charge"] },
      { kanji: "段", meanings: ["step", "stage", "paragraph"] },
      { kanji: "階", meanings: ["floor", "step", "rank"] },
      { kanji: "層", meanings: ["layer", "stratum"] },
      { kanji: "群", meanings: ["group", "crowd", "flock"] },
      { kanji: "団", meanings: ["group", "organization", "round"] },
      { kanji: "集", meanings: ["gather", "collect", "anthology"] },
      { kanji: "族", meanings: ["tribe", "family", "clan"] },
      { kanji: "派", meanings: ["school", "faction", "dispatch"] },
      { kanji: "派", meanings: ["sect", "party", "dispatch"] },
      { kanji: "流", meanings: ["flow", "style", "school"] },
      { kanji: "系", meanings: ["lineage", "system"] },
      { kanji: "種", meanings: ["type", "kind", "species"] },
      { kanji: "類", meanings: ["type", "kind", "class"] },
      { kanji: "品", meanings: ["goods", "item", "quality"] },
      { kanji: "格", meanings: ["status", "rank", "case"] },
      { kanji: "級", meanings: ["rank", "grade", "class"] },
      { kanji: "等", meanings: ["grade", "equal", "etc"] },
      { kanji: "順", meanings: ["order", "sequence"] },
      { kanji: "序", meanings: ["order", "beginning"] },
      { kanji: "位", meanings: ["rank", "status", "place"] },
      { kanji: "置", meanings: ["place", "put", "leave"] },
      { kanji: "成", meanings: ["become", "result", "form"] },
      { kanji: "形", meanings: ["shape", "form", "type"] },
      { kanji: "態", meanings: ["state", "condition", "situation"] },
      { kanji: "様", meanings: ["manner", "way", "appearance"] },
      { kanji: "方", meanings: ["direction", "way", "side"] },
      { kanji: "式", meanings: ["type", "style", "formula"] },
      { kanji: "様", meanings: ["pattern", "sample"] },
      { kanji: "例", meanings: ["example", "instance"] },
      { kanji: "表", meanings: ["table", "surface", "display"] },
      { kanji: "図", meanings: ["figure", "diagram", "map"] },
      { kanji: "案", meanings: ["idea", "plan", "proposal"] },
      { kanji: "想", meanings: ["think", "imagine"] },
      { kanji: "論", meanings: ["theory", "argument", "discussion"] },
      { kanji: "説", meanings: ["theory", "opinion", "explanation"] },
      { kanji: "証", meanings: ["proof", "evidence", "certificate"] },
      { kanji: "拠", meanings: ["basis", "evidence"] },
      { kanji: "根", meanings: ["root", "origin", "foundation"] },
      { kanji: "本", meanings: ["origin", "base", "main"] },
      { kanji: "元", meanings: ["origin", "former", "element"] },
      { kanji: "源", meanings: ["source", "origin", "spring"] },
      { kanji: "初", meanings: ["beginning", "first", "start"] },
      { kanji: "早", meanings: ["early", "quick"] },
      { kanji: "先", meanings: ["ahead", "former", "first"] },
      { kanji: "際", meanings: ["occasion", "time", "when"] },
      { kanji: "後", meanings: ["behind", "after", "later"] },
      { kanji: "継", meanings: ["succeed", "continue"] },
      { kanji: "嗣", meanings: ["heir", "successor"] },
      { kanji: "余", meanings: ["extra", "surplus", "remainder"] },
      { kanji: "剰", meanings: ["surplus", "excess"] },
      { kanji: "越", meanings: ["exceed", "go over", "excess"] },
      { kanji: "過", meanings: ["excess", "past", "mistake"] },
      { kanji: "超", meanings: ["surpass", "exceed", "super"] },
      { kanji: "限", meanings: ["limit", "boundary", "period"] },
      { kanji: "際", meanings: ["edge", "occasion"] },
      { kanji: "迄", meanings: ["until", "up to"] },
      { kanji: "迫", meanings: ["approach", "press"] },
      { kanji: "据", meanings: ["place", "set", "establish"] },
      { kanji: "距", meanings: ["distance"] },
      { kanji: "遠", meanings: ["far", "distant"] },
      { kanji: "近", meanings: ["near", "close"] },
      { kanji: "側", meanings: ["side", "beside"] },
      { kanji: "面", meanings: ["face", "side", "surface"] },
      { kanji: "方", meanings: ["person", "side", "direction"] },
      { kanji: "隣", meanings: ["neighbor", "next to"] },
      { kanji: "周", meanings: ["around", "circumference"] },
      { kanji: "囲", meanings: ["surround", "encircle"] },
      { kanji: "環", meanings: ["ring", "circle", "loop"] },
      { kanji: "巻", meanings: ["volume", "roll", "wind"] },
      { kanji: "帯", meanings: ["zone", "belt", "carry"] },
      { kanji: "扱", meanings: ["handle", "treat", "deal"] },
      { kanji: "扱", meanings: ["manage", "handle"] },
      { kanji: "処", meanings: ["place", "where", "deal"] },
      { kanji: "処", meanings: ["situation", "where"] },
      { kanji: "置", meanings: ["put", "place", "set"] },
      { kanji: "任", meanings: ["assign", "entrust"] },
      { kanji: "役", meanings: ["duty", "role", "part"] },
      { kanji: "職", meanings: ["occupation", "position", "post"] },
      { kanji: "務", meanings: ["duty", "task", "matter"] },
      { kanji: "令", meanings: ["order", "command", "law"] },
      { kanji: "指", meanings: ["finger", "point", "point out"] },
      { kanji: "示", meanings: ["show", "indicate", "display"] },
      { kanji: "唆", meanings: ["instigate", "suggest"] },
      { kanji: "導", meanings: ["guide", "lead", "bring"] },
      { kanji: "促", meanings: ["urge", "prompt"] },
      { kanji: "促", meanings: ["press", "push"] },
      { kanji: "促", meanings: ["urge", "hasten"] },
      { kanji: "請", meanings: ["request", "ask", "appeal"] },
      { kanji: "願", meanings: ["wish", "request", "desire"] },
      { kanji: "祈", meanings: ["pray", "wish"] },
      { kanji: "祷", meanings: ["pray", "prayer"] },
      { kanji: "呼", meanings: ["call", "name", "summon"] },
      { kanji: "名", meanings: ["name", "reputation", "title"] },
      { kanji: "称", meanings: ["name", "call", "title"] },
      { kanji: "号", meanings: ["number", "name", "issue"] },
      { kanji: "題", meanings: ["title", "subject", "topic"] },
      { kanji: "目", meanings: ["title", "item", "heading"] },
      { kanji: "項", meanings: ["item", "clause", "paragraph"] },
      { kanji: "款", meanings: ["clause", "article"] },
      { kanji: "条", meanings: ["article", "clause", "strip"] },
      { kanji: "約", meanings: ["promise", "agreement", "about"] },
      { kanji: "定", meanings: ["fix", "decide", "rule"] },
      { kanji: "決", meanings: ["decide", "settle", "resolve"] },
      { kanji: "解", meanings: ["open", "divide", "solve"] },
      { kanji: "抉", meanings: ["scrape", "dig out"] },
      { kanji: "却", meanings: ["abandon", "reject"] },
      { kanji: "斥", meanings: ["reject", "repel"] },
      { kanji: "排", meanings: ["exclude", "expel", "line up"] },
      { kanji: "除", meanings: ["remove", "exclude", "divide"] },
      { kanji: "廃", meanings: ["abolish", "abandon", "disuse"] },
      { kanji: "止", meanings: ["stop", "cease", "halt"] },
      { kanji: "禁", meanings: ["prohibit", "ban"] },
      { kanji: "禁", meanings: ["forbidden", "taboo"] },
      { kanji: "罷", meanings: ["suspend", "stop", "remove"] },
      { kanji: "辞", meanings: ["resign", "refuse", "words"] },
      { kanji: "譲", meanings: ["yield", "give way", "concede"] },
      { kanji: "歩", meanings: ["walk", "step", "progress"] },
      { kanji: "進", meanings: ["advance", "go forward", "promote"] },
      { kanji: "捗", meanings: ["progress", "advance"] },
      { kanji: "捗", meanings: ["make progress"] },
    ],
    N2: [
      { kanji: "侍", meanings: ["samurai", "wait", "attend"] },
      { kanji: "俳", meanings: ["haiku", "go around"] },
      { kanji: "倫", meanings: ["ethics", "morality"] },
      { kanji: "儀", meanings: ["ceremony", "formality"] },
      { kanji: "允", meanings: ["allow", "permit"] },
      { kanji: "忙", meanings: ["busy", "hectic"] },
      { kanji: "忽", meanings: ["overlook", "neglect"] },
      { kanji: "怖", meanings: ["fear", "frighten"] },
      { kanji: "怪", meanings: ["strange", "weird", "mystery"] },
      { kanji: "恥", meanings: ["shame", "embarrassment"] },
      { kanji: "恨", meanings: ["grudge", "resentment"] },
      { kanji: "悔", meanings: ["regret", "remorse"] },
      { kanji: "惰", meanings: ["lazy", "indolence"] },
      { kanji: "慮", meanings: ["consider", "think"] },
      { kanji: "懐", meanings: ["bosom", "pocket", "nostalgia"] },
      { kanji: "懲", meanings: ["punish", "discipline"] },
      { kanji: "戒", meanings: ["caution", "precept"] },
      { kanji: "戟", meanings: ["halberd", "spear"] },
      { kanji: "撃", meanings: ["hit", "attack", "strike"] },
      { kanji: "撤", meanings: ["withdraw", "retreat"] },
      { kanji: "撞", meanings: ["clash", "strike", "hit"] },
      { kanji: "撤", meanings: ["remove", "pull back"] },
      { kanji: "撹", meanings: ["disturb", "confuse", "stir"] },
      { kanji: "攫", meanings: ["seize", "snatch"] },
      { kanji: "攻", meanings: ["attack", "assault", "criticize"] },
      { kanji: "攘", meanings: ["repel", "drive away"] },
      { kanji: "敏", meanings: ["quick", "smart", "alert"] },
      { kanji: "敦", meanings: ["kind", "sincere", "honest"] },
      { kanji: "敵", meanings: ["enemy", "rival", "opponent"] },
      { kanji: "敷", meanings: ["spread", "lay", "apply"] },
      { kanji: "斎", meanings: ["purify", "vegetarian"] },
      { kanji: "斡", meanings: ["mediate", "arrange"] },
      { kanji: "旋", meanings: ["rotate", "spin", "turn"] },
      { kanji: "旬", meanings: ["period", "10-day week"] },
      { kanji: "昌", meanings: ["prosperous", "flourish"] },
      { kanji: "昭", meanings: ["bright", "clear", "shine"] },
      { kanji: "晋", meanings: ["promote", "advance"] },
      { kanji: "晞", meanings: ["dry", "wait"] },
      { kanji: "晦", meanings: ["dark", "obscure"] },
      { kanji: "暉", meanings: ["shine", "glitter", "brilliant"] },
      { kanji: "暦", meanings: ["calendar", "almanac"] },
      { kanji: "暴", meanings: ["violent", "sudden", "rough"] },
      { kanji: "曜", meanings: ["day of week"] },
      { kanji: "曾", meanings: ["ever", "formerly"] },
      { kanji: "朕", meanings: ["I", "me"] },
      { kanji: "朗", meanings: ["bright", "clear", "cheerful"] },
      { kanji: "朝", meanings: ["morning", "dawn", "dynasty"] },
      { kanji: "朱", meanings: ["red", "vermillion"] },
      { kanji: "朴", meanings: ["plain", "simple", "wood"] },
      { kanji: "杏", meanings: ["apricot"] },
      { kanji: "杖", meanings: ["cane", "stick", "staff"] },
      { kanji: "杜", meanings: ["shrine", "prevent"] },
      { kanji: "杞", meanings: ["wild jujube tree"] },
      { kanji: "杪", meanings: ["tip", "end"] },
      { kanji: "杭", meanings: ["pile", "stake", "peg"] },
      { kanji: "杯", meanings: ["cup", "glass", "counter"] },
      { kanji: "杷", meanings: ["rake", "comb"] },
      { kanji: "杼", meanings: ["shuttle", "weaving"] },
      { kanji: "枏", meanings: ["cypress"] },
      { kanji: "枇", meanings: ["loquat tree"] },
      { kanji: "枉", meanings: ["bend", "wrong", "injustice"] },
      { kanji: "枋", meanings: ["plank", "board"] },
      { kanji: "枕", meanings: ["pillow"] },
      { kanji: "枚", meanings: ["counter", "sheet", "piece"] },
      { kanji: "枝", meanings: ["branch", "twig"] },
      { kanji: "枢", meanings: ["pivot", "hinge"] },
      { kanji: "枣", meanings: ["date tree", "jujube"] },
      { kanji: "枥", meanings: ["stall", "stable"] },
      { kanji: "枦", meanings: ["juniper"] },
      { kanji: "枧", meanings: ["channel", "conduit"] },
      { kanji: "枨", meanings: ["stake", "post"] },
      { kanji: "枩", meanings: ["pine tree"] },
      { kanji: "枫", meanings: ["maple"] },
      { kanji: "枬", meanings: ["dry", "withered"] },
      { kanji: "枭", meanings: ["owl", "fierce"] },
      { kanji: "枰", meanings: ["board game", "flat"] },
      { kanji: "枱", meanings: ["table", "stand"] },
      { kanji: "枲", meanings: ["net", "sieve"] },
      { kanji: "枳", meanings: ["trifoliate orange"] },
      { kanji: "枴", meanings: ["cane", "stick"] },
      { kanji: "枵", meanings: ["empty", "hollow"] },
      { kanji: "枸", meanings: ["goji berry", "frame"] },
      { kanji: "枹", meanings: ["drumstick", "stick"] },
      { kanji: "枺", meanings: ["branch"] },
      { kanji: "枻", meanings: ["small boat"] },
      { kanji: "枼", meanings: ["leaf", "thin"] },
      { kanji: "枽", meanings: ["straw", "hay"] },
      { kanji: "枾", meanings: ["persimmon"] },
      { kanji: "柀", meanings: ["fence", "railing"] },
      { kanji: "柁", meanings: ["rudder", "helm"] },
      { kanji: "柂", meanings: ["rudder", "steer"] },
      { kanji: "柃", meanings: ["privet"] },
      { kanji: "柄", meanings: ["handle", "grip", "pattern"] },
      { kanji: "柅", meanings: ["check", "stop"] },
      { kanji: "柆", meanings: ["oar", "paddle"] },
      { kanji: "柇", meanings: ["pole", "stake"] },
      { kanji: "柈", meanings: ["wooden plate"] },
      { kanji: "柉", meanings: ["palisade", "fence"] },
      { kanji: "柊", meanings: ["holly", "ilex"] },
      { kanji: "柋", meanings: ["firewood"] },
      { kanji: "柌", meanings: ["wooden pin"] },
      { kanji: "柍", meanings: ["pillar", "post"] },
      { kanji: "柎", meanings: ["calyx", "flower cup"] },
      { kanji: "柏", meanings: ["cypress", "oak"] },
      { kanji: "某", meanings: ["pail", "bucket"] },
      { kanji: "柑", meanings: ["citrus", "orange"] },
      { kanji: "柒", meanings: ["seven", "lacquer"] },
      { kanji: "染", meanings: ["comb", "rake"] },
      { kanji: "柔", meanings: ["soft", "flexible", "gentle"] },
      { kanji: "柕", meanings: ["support", "prop"] },
      { kanji: "柖", meanings: ["place", "put"] },
      { kanji: "柗", meanings: ["tiller", "lever"] },
      { kanji: "柘", meanings: ["mulberry", "fustian tree"] },
      { kanji: "柙", meanings: ["cage", "prison"] },
      { kanji: "柚", meanings: ["grapefruit", "pomelo"] },
      { kanji: "柛", meanings: ["plumb line"] },
      { kanji: "柜", meanings: ["cabinet", "chest"] },
      { kanji: "柝", meanings: ["night watch", "sound"] },
      { kanji: "柞", meanings: ["oak tree"] },
      { kanji: "柟", meanings: ["oak tree"] },
      { kanji: "柠", meanings: ["lemon"] },
      { kanji: "柡", meanings: ["elm tree"] },
      { kanji: "柢", meanings: ["root", "base"] },
      { kanji: "柣", meanings: ["wooden instrument"] },
      { kanji: "柤", meanings: ["wooden comb"] },
    ],
    N1: [
      { kanji: "殮", meanings: ["to lay in coffin"] },
      { kanji: "殯", meanings: ["wake", "lying in state"] },
      { kanji: "殰", meanings: ["corpse"] },
      { kanji: "殱", meanings: ["annihilate", "destroy"] },
      { kanji: "殲", meanings: ["annihilate", "eliminate"] },
      { kanji: "殳", meanings: ["pestle", "weapon"] },
      { kanji: "殴", meanings: ["beat", "strike", "hit"] },
      { kanji: "段", meanings: ["step", "level", "stage"] },
      { kanji: "殷", meanings: ["earnest", "attentive"] },
      { kanji: "殸", meanings: ["shell", "bone"] },
      { kanji: "殹", meanings: ["wail", "lament"] },
      { kanji: "殺", meanings: ["kill", "murder", "slay"] },
      { kanji: "殻", meanings: ["shell", "husk"] },
      { kanji: "殼", meanings: ["shell", "husk"] },
      { kanji: "殾", meanings: ["grow", "develop"] },
      { kanji: "殿", meanings: ["palace", "hall", "bottom"] },
      { kanji: "毀", meanings: ["destroy", "break", "damage"] },
      { kanji: "毁", meanings: ["destroy", "ruin"] },
      { kanji: "毂", meanings: ["hub", "center"] },
      { kanji: "毃", meanings: ["beard"] },
      { kanji: "毄", meanings: ["pluck", "pull"] },
      { kanji: "毅", meanings: ["courageous", "strong", "firm"] },
      { kanji: "毆", meanings: ["beat", "strike", "hit"] },
      { kanji: "毈", meanings: ["hair", "fur"] },
      { kanji: "毉", meanings: ["doctor", "medicine"] },
      { kanji: "毊", meanings: ["rough", "coarse"] },
      { kanji: "毋", meanings: ["mother", "do not"] },
      { kanji: "毌", meanings: ["connect", "unite"] },
      { kanji: "母", meanings: ["hair"] },
      { kanji: "毎", meanings: ["every", "each"] },
      { kanji: "毎", meanings: ["each", "every time"] },
      { kanji: "每", meanings: ["beard", "whiskers"] },
      { kanji: "毐", meanings: ["poisonous", "venom"] },
      { kanji: "毑", meanings: ["hair"] },
      { kanji: "毒", meanings: ["poison", "toxic", "venom"] },
      { kanji: "毓", meanings: ["nourish", "develop", "raise"] },
      { kanji: "比", meanings: ["hairless", "bare"] },
      { kanji: "毖", meanings: ["prudent", "careful", "cautious"] },
      { kanji: "毗", meanings: ["beside", "near", "border"] },
      { kanji: "毘", meanings: ["beside", "near"] },
      { kanji: "毙", meanings: ["die", "fall", "defeat"] },
      { kanji: "毚", meanings: ["rabbit", "hare"] },
      { kanji: "毛", meanings: ["hair", "fur", "feather"] },
      { kanji: "毜", meanings: ["fluffy", "shaggy"] },
      { kanji: "毝", meanings: ["hair", "fur"] },
      { kanji: "毞", meanings: ["hair", "fur"] },
      { kanji: "毟", meanings: ["pluck", "pull"] },
      { kanji: "毠", meanings: ["bald"] },
      { kanji: "毡", meanings: ["felt", "rug"] },
      { kanji: "毢", meanings: ["hair", "fur"] },
      { kanji: "毣", meanings: ["hair", "fur"] },
      { kanji: "毤", meanings: ["hair", "fur"] },
      { kanji: "毥", meanings: ["scratch", "comb"] },
      { kanji: "毦", meanings: ["shaggy", "rough"] },
      { kanji: "毧", meanings: ["fluffy", "soft"] },
      { kanji: "毨", meanings: ["hair", "fur"] },
      { kanji: "毩", meanings: ["hair", "fur"] },
      { kanji: "毪", meanings: ["hairless"] },
      { kanji: "毫", meanings: ["hair", "fine", "slight"] },
      { kanji: "毬", meanings: ["ball", "sphere", "globe"] },
      { kanji: "毭", meanings: ["hair", "fur"] },
      { kanji: "毮", meanings: ["hair", "fur"] },
      { kanji: "毯", meanings: ["blanket", "carpet"] },
      { kanji: "毰", meanings: ["ball", "sphere"] },
      { kanji: "毱", meanings: ["ball", "shuttle"] },
      { kanji: "毲", meanings: ["hair", "fur"] },
      { kanji: "毳", meanings: ["fluffy hair", "down"] },
      { kanji: "毴", meanings: ["hair", "fur"] },
      { kanji: "毵", meanings: ["shaggy", "long hair"] },
      { kanji: "毶", meanings: ["bald", "hairless"] },
      { kanji: "毷", meanings: ["hair", "fur"] },
      { kanji: "毸", meanings: ["hair", "fur"] },
      { kanji: "毹", meanings: ["hair", "fur"] },
      { kanji: "毺", meanings: ["fluffy", "soft"] },
      { kanji: "毻", meanings: ["hair", "fur"] },
      { kanji: "毼", meanings: ["hair", "fur"] },
      { kanji: "毽", meanings: ["shuttlecock"] },
      { kanji: "毾", meanings: ["hair", "fur"] },
      { kanji: "毿", meanings: ["shaggy", "rough"] },
      { kanji: "氀", meanings: ["felt", "rug"] },
      { kanji: "氁", meanings: ["hair", "fur"] },
      { kanji: "氂", meanings: ["yak hair", "fine hair"] },
      { kanji: "氃", meanings: ["mold", "spore"] },
      { kanji: "氄", meanings: ["wind", "breeze"] },
      { kanji: "氅", meanings: ["cape", "cloak"] },
      { kanji: "氆", meanings: ["cloth", "fabric"] },
      { kanji: "氇", meanings: ["musk", "fragrant"] },
      { kanji: "氈", meanings: ["felt", "rug"] },
      { kanji: "氉", meanings: ["filter", "strain"] },
      { kanji: "氊", meanings: ["felt", "rug"] },
      { kanji: "氋", meanings: ["fragrant", "scent"] },
      { kanji: "氌", meanings: ["cloth", "fabric"] },
      { kanji: "氍", meanings: ["coarse cloth", "sackcloth"] },
      { kanji: "氎", meanings: ["paper", "sheet"] },
      { kanji: "氏", meanings: ["clan", "family", "person"] },
      { kanji: "氐", meanings: ["foundation", "base"] },
      { kanji: "民", meanings: ["water rising"] },
      { kanji: "氒", meanings: ["hydrogen"] },
      { kanji: "氓", meanings: ["common people", "ruffian"] },
      { kanji: "气", meanings: ["white clouds"] },
      { kanji: "氕", meanings: ["ice"] },
      { kanji: "氖", meanings: ["neon"] },
      { kanji: "気", meanings: ["snow"] },
      { kanji: "氘", meanings: ["deuterium"] },
      { kanji: "氙", meanings: ["xenon"] },
      { kanji: "氚", meanings: ["tritium"] },
    ],
  };

// Format kanji data according to your structure
function formatKanjiData() {
  const result = [];
  let id = 1;

  for (const [level, kanjiList] of Object.entries(JLPT_KANJI)) {
    for (const kanjiEntry of kanjiList) {
      result.push({
        id: `kanji-${id}`,
        kanji: kanjiEntry.kanji,
        meaning: kanjiEntry.meanings.join(", "),
        onyomi: ["[onyomi data]"], // You'll need comprehensive onyomi data
        kunyomi: ["[kunyomi data]"], // You'll need comprehensive kunyomi data
        strokes: 0, // You'll need stroke count data
        jlpt: level,
        radicals: [kanjiEntry.kanji],
        examples: [
          {
            word: kanjiEntry.kanji,
            reading: "[reading]",
            meaning: kanjiEntry.meanings[0],
          },
        ],
      });
      id++;
    }
  }

  return result;
}

// VOCABULARY DATA - Comprehensive N5-N1
const VOCABULARY_FRAMEWORK = {
  N5: {
    label: "N5 - Beginner",
    count: 100,
    categories: [
      "daily-life",
      "family",
      "food",
      "time",
      "numbers",
      "body-parts",
    ],
  },
  N4: {
    label: "N4 - Lower-Intermediate",
    count: 200,
    categories: [
      "emotions",
      "nature",
      "travel",
      "work",
      "education",
      "health",
    ],
  },
  N3: {
    label: "N3 - Intermediate",
    count: 300,
    categories: [
      "abstract",
      "business",
      "technology",
      "society",
      "culture",
      "environment",
    ],
  },
  N2: {
    label: "N2 - Upper-Intermediate",
    count: 400,
    categories: [
      "politics",
      "economics",
      "literature",
      "philosophy",
      "science",
      "specialized",
    ],
  },
  N1: {
    label: "N1 - Advanced",
    count: 500,
    categories: [
      "rare-words",
      "classical",
      "technical",
      "specialized-fields",
      "idioms",
      "advanced-concepts",
    ],
  },
};

// GRAMMAR DATA - Comprehensive N5-N1
const GRAMMAR_FRAMEWORK = {
  N5: {
    label: "N5 - Beginner",
    categories: [
      "particles",
      "copula",
      "basic-verbs",
      "adjectives",
      "polite-forms",
    ],
  },
  N4: {
    label: "N4 - Lower-Intermediate",
    categories: [
      "causative",
      "passive",
      "conditional",
      "conjunctions",
      "informal-speech",
    ],
  },
  N3: {
    label: "N3 - Intermediate",
    categories: [
      "advanced-conditionals",
      "potential-forms",
      "transitivity",
      "formal-patterns",
      "subjunctive",
    ],
  },
  N2: {
    label: "N2 - Upper-Intermediate",
    categories: [
      "archaic-forms",
      "complex-sentences",
      "rhetorical-patterns",
      "specialized-grammar",
      "nuanced-particles",
    ],
  },
  N1: {
    label: "N1 - Advanced",
    categories: [
      "rare-particles",
      "literary-forms",
      "specialized-grammar",
      "abstract-patterns",
      "classical-japanese",
    ],
  },
};

console.log("JLPT N5-N1 Data Structure Framework");
console.log("=====================================\n");

console.log("KANJI BREAKDOWN:");
for (const [level, kanjiData] of Object.entries(JLPT_KANJI)) {
  console.log(`${level}: ${kanjiData.length} kanji`);
}

console.log("\n\nVOCABULARY FRAMEWORK:");
for (const [level, vocabData] of Object.entries(VOCABULARY_FRAMEWORK)) {
  console.log(`${level} (${vocabData.label}): ~${vocabData.count} words`);
}

console.log("\n\nGRAMMAR FRAMEWORK:");
for (const [level, grammarData] of Object.entries(GRAMMAR_FRAMEWORK)) {
  console.log(`${level} (${grammarData.label}): ${grammarData.categories.join(", ")}`);
}

export { formatKanjiData, JLPT_KANJI, VOCABULARY_FRAMEWORK, GRAMMAR_FRAMEWORK };
